### ISSUE TITLE
wave.ReadWaveFile segfault on 24bit wav files

### ISSUE THREAD

**Issue by gkuchta** [DylanMeeus/GoAudio#8]
Greetings!

It looks like parseRawData() segfaults on 24bit wav files, because there's no conversion function defined here

```golang
	byteSizeToIntFunc = map[int]bytesToIntF{
		16: bits16ToInt,
		32: bits32ToInt,
	}
```

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x10a3643]

goroutine 1 [running]:
github.com/DylanMeeus/GoAudio/wave.parseRawData(0xc00010000c, 0x4, 0x102880, 0x10, 0x1, 0x2, 0xac44, 0x40998, 0x6, 0x18, ...)
	...go/pkg/mod/github.com/!dylan!meeus/!go!audio@v0.13.0/wave/reader.go:145 +0x143
github.com/DylanMeeus/GoAudio/wave.ReadWaveFile(0x10d7ea8, 0x13, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
```
I imagine the omission is due to there being no math constant defined for a max 24bit integer, which is understandable. It looks like other packages work around this by simply defining their own -- either by defining it as 8bitmax+16bitmax, or, in the case of mysql:

```golang
const (
	MaxUint24 = 1<<24 - 1
	MaxInt24  = 1<<23 - 1
	MinInt24  = -1 << 23
)
```

I'm happy to drop a PR if it'd be helpful, but I figured I'd just give you a heads up first, as I'm not 100% sure that my solution is correct

Cheers,

**Comment by DylanMeeus** [comment]
Hey @gkuchta, thanks for bringing that to my attention. 
I think the approach you mentioned is good, I'd definitely be happy to merge a PR that adds this feature!

**Comment by gkuchta** [comment]
Cool! I'll take a crack at it! I wound up going another route on my project, but I'm always happy to pay stuff forward. Cheers!

**Comment by DylanMeeus** [comment]
@gkuchta Good luck! Glad you found another way for your project :smile:

**Comment by gkuchta** [comment]
@DylanMeeus sorry about the slow turn around. got a little busy. here's an idea for how to address it, if you want to in the future. cheers, and happy year https://github.com/DylanMeeus/GoAudio/pull/11
